name: travel_wisata_lokal
description: A Flutter project for Travel Wisata Lokal (basic starter)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.0
  image_picker: ^0.8.7+5
  geolocator: ^9.0.2
  google_maps_flutter: ^2.5.0
  permission_handler: ^11.1.0
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  shared_preferences: ^2.2.2
  # URL Launcher
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/marker.png
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter_18pt-Bold.ttf
          weight: 700
